### ISSUE TITLE
hared.go TLS support

### ISSUE THREAD

**Issue by juzam** [jpmens/hared-hare#15]
My Idea is to have a boolean switch in `HARED_INI` like so:
`mqtttls`
So we can have tls support on any port (and not relying on checking if  default tls port `8883` is defined)
Golang handles mqtt connection strings like this:
* unencrypted mqtt : `tcp://hostname:port`
* encrypted mqtt: `ssl://hostname:port`

so the first part of the connection which is now hardcoded as `tcp://` must be handled accordingly.

I would also add another INI field to specify a CA file, so one can  use certificates not emitted by "known" CAs, without falling back to an insecure "trust everything" scenario.
something like:
`mqttCAfile`

**Comment by jpmens** [comment]
I dislike all the 't' in `mqtttls` as it's bound to cause double-takes. Maybe `mqtt_tls` or just `tls`? (I realize that could be misinterpreted to mean the UDP listener)

Since Golang uses URI, why don't we do that too? Drop the host/port settings and add a `mqtt_uri` or some some and expect administrator to correctly populate that. Probably easiest?

ACK to the `mqttCAfile`, and as you propose CAPS in that, then let's go the whole hog and do `mqttURI`.

**Comment by juzam** [comment]
Ok, I think I'm sold on `mqttURI` and `mqttCAfile`.
As per [paho.mqtt.golang Documentation](https://godoc.org/github.com/eclipse/paho.mqtt.golang#ClientOptions.AddBroker) by using a string directly as an URI, we gain the ability to connect via web sockets, in addition to  plain and encrypted mqtt.

So I think dropping hostname/port support is a necessary pain.

mixed case INI fields help readability, in my opinion, but internally the package I use (gopkg.in/gcfg.v1) deliberately ignore case in sections and variable names. 

so far the new INI format looks like this:

```
[defaults]
verbose    = False
udpHost    = localhost
udpPort    = 8035
mqttURI    = tcp://127.0.0.1:1883
mqttTopic  = logging/hare
mqttQos    = 1
mqttUser   = username
mqttPass   = password
mqttCAfile = full path to cafile
```

Defaults:

```
[defaults]
verbose    = False
udpHost    = 0.0.0.0
udpPort    = 8035
mqttURI    = tcp://127.0.0.1:1883
mqttTopic  = logging/hare
mqttQos    = 1
```

**Comment by jpmens** [comment]
Dropping hostname/port support is no pain; let's do it, but while you're at it, let's clarify those names a bit:

```
listenhost => udpHost
listenport => udpPort

topic => mqttTopic
```

I think that would look more sensible, but I'm easy. You decide, I merge. :-)

**Comment by juzam** [comment]
Ok, i'll even throw in an `mqttQos` :-)

**Comment by jpmens** [comment]
Attaboy. Default 1

**Comment by jpmens** [comment]
Thank you very much; this is very good. I've tested authentication (we do not need client-cert authentication I think), and I've tested TLS.
