### ISSUE TITLE
hared.go/py should obtain remote's address

### ISSUE THREAD

**Issue by jpmens** [jpmens/hared-hare#16]
Upon testing with the *original* tiny Python implementation I notice we've forgotten to obtain the remote client's (i.e. `hare`'s) IP address. This must have happened when I implemented JSON sending on the client and thought I wouldn't have to decompose server-side.

This remote address is important and we should add it.

**Comment by juzam** [comment]
This is non trivial for me at the moment, so the enhancement to `hared.go` has no ETA. 
I know how to extract the remote address from oob UDP connection data,  I have to heavily test the part for adding that field back to JSON.

**Comment by jpmens** [comment]
I wanted to show off that I'm great at copy/pasting code off the internets, and I accomplished this:

```json
{"hostname":"tigg","remote":"1.2.3.4","rhost":"this.host","service":"sshd","tst":1.522485183e+09,"tty":"console","user":"jjolie"}
```

I was hugely pleased at what I'd accomplished until I looked more closely to see that `tst` is screwed (at least visually). So, I am giving up, but I'll leave the fruit of my experiments here so that you can move them to /dev/null.

```patch
diff --git a/hared/contrib/hared.go b/hared/contrib/hared.go
index 8dd0106..faf35cf 100644
--- a/hared/contrib/hared.go
+++ b/hared/contrib/hared.go
@@ -66,15 +66,19 @@ func main() {

         message := string(buf[0:n])

-        if cfg.Defaults.Verbose {
-           fmt.Println(message)
-        }
-
         var data map[string]interface{}
         if  error := json.Unmarshal([]byte(message), &data); error != nil {
             continue
         }

+       data["remote"] = "1.2.3.4"
+       rawpayload, _ := json.Marshal(data)
+       payload := string(rawpayload)
+
+        if cfg.Defaults.Verbose {
+           fmt.Println(payload)
+        }
+
         opts := mqtt.NewClientOptions().AddBroker(cfg.Defaults.MqttURI)

         if len(cfg.Defaults.MqttUser) > 0 && len(cfg.Defaults.MqttPass) > 0 {
@@ -95,7 +99,7 @@ func main() {
                     fmt.Println(token.Error())
                     continue
         }
-        if token := c.Publish(cfg.Defaults.MqttTopic, cfg.Defaults.MqttQos, false, message); token.
+        if token := c.Publish(cfg.Defaults.MqttTopic, cfg.Defaults.MqttQos, false, payload); token.
                     fmt.Println(token.Error())
         }
        c.Disconnect(250)
```

I promise to not attempt to do Golang until I've studied it. :-)

**Comment by juzam** [comment]
I think I have it, incoming PR :) Thanks for the much needed help.
btw, my usual approach to programming is a mix of RTFM, copy paste and witchcraft ;-)

**Comment by jpmens** [comment]
Thank you again, @juzam: this is wonderful. I have now, as promised, promoted `hared.go` to our main daemon. :-)
