### ISSUE TITLE
does hared.ini take ssl:// or tls:// or both?

### ISSUE THREAD

**Issue by dlangille** [jpmens/hared-hare#21]
While reading https://github.com/jpmens/hared-hare/blob/master/daemon/README.md

line 34: # for TLS MQTT:    ssl://hostname.example.com:8883

line 42: # path to CA certificate file if mqttURI starts with "tls://"

That seems to contradict, but my testing indicates that both ssl:// and tls:// work

Are they synonyms?

**Comment by jpmens** [comment]
They are synonyms.

**Comment by juzam** [comment]
the `paho.mtt.golang`  [documentation](https://godoc.org/github.com/eclipse/paho.mqtt.golang#ClientOptions.AddBroker) lists these type of scheme:
`"scheme" is one of "tcp", "ssl", or "ws"`
But I've just successfully tested a broker previously configured with `ssl://`  with `tls://` and it works just fine.

So, they are indeed synonyms (even if the official package documentation doesn't say so)

To expand on the scheme thing, a `wss://` scheme should work too (that's secure websockets) even if it's not listed. 

thanks @jpmens, you're faster than me :)
