### ISSUE TITLE
hared.go should publish received JSON

### ISSUE THREAD

**Issue by jpmens** [jpmens/hared-hare#7]
hared (the daemon) used to format a received message and publish it as JSON. The _hare_ client now _produces_ JSON itself so this step is no longer necessary/desired.

Our Python implementation of _hared_ already caters for that. It would be great if the Go version would also. @juzam I'm sure you're just dying to do this? :-)

**Comment by juzam** [comment]
@jpmens no problem :-) everything that reduces complexity is more than fine with me.
