### ISSUE TITLE
hared.go should support ini style config

### ISSUE THREAD

**Issue by juzam** [jpmens/hared-hare#9]
possibly via [https://gopkg.in/gcfg.v1](https://gopkg.in/gcfg.v1) and os.Getenv("HARED_INI")

**Comment by juzam** [comment]
closed via https://github.com/jpmens/hared-hare/pull/10

**Comment by jpmens** [comment]
I have patched **your** Go program. 1000 apologies. :-)

I noticed that _hared_ didn't complain on missing/bad INI file. A look at how you did it made me shove a single closing brace to provide for that.

**Comment by juzam** [comment]
argh! :( thank you!  sorry about that :|

**Comment by jpmens** [comment]
No apologies please. I'm a PITA in that respect. (Our OwnTracks colleagues could tell you a story (or a hundred) of how I do that all the time.  :-)
